### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Gregorio012#1]
[SintesisSG_Gregorio Osorio Sarmiento.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Gregorio012/files/12704140/SintesisSG_Gregorio.Osorio.Sarmiento.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
